name: Setup repo
description: Runs all steps to setup the repo (install node_modules, build, etc...)
inputs:
  registry-token:
    description: 'PAT to access registries'
runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
        echo "::set-output name=version::$(yarn -v)"

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}

        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: echo "//npm.pkg.github.com/:_authToken=$SDK_READ_ACCESS_TOKEN" >> .npmrc && yarn install --frozen-lockfile --verbose  && rm -f .npmrc
      env:
        SDK_READ_ACCESS_TOKEN: ${{ inputs.registry-token }}
